services:
  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    # AOF activated, RDB activated, every 15 min if at least 1 key changed,
    # every 5 min if at least 10 keys changed, every 1 min if at least 10000 keys changed
    command: redis-server --appendonly yes --save 900 1 --save 300 10 --save 60 10000
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 5

  wait-for-db-to-be-ready:
    image: hello-world
    depends_on:
      redis:
        condition: service_healthy
